package C4::AgrovocWSService;
# Generated by SOAP::Lite (v1.26) for Perl -- soaplite.com
# Copyright (C) 2000-2006 Paul Kulchenko, Byrne Reese
# -- generated at [Mon May 21 17:00:34 2018]
# -- generated from http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS?wsdl
my %methods = (
'getTermByLanguage' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'termcode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'language', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermByLanguage
'getConceptInfoByClassName' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'conceptName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getConceptInfoByClassName
'getAgrovocCSLanguages' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
    ], # end parameters
  }, # end getAgrovocCSLanguages
'getPossibleRelationsFromConceptURI' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'conceptURI', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'relationType', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getPossibleRelationsFromConceptURI
'getConceptByURI' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'conceptURI', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getConceptByURI
'getRejectedConcepts' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'authorityFile', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'dateFrom', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'dateTo', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'integerFrom', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'integerTo', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getRejectedConcepts
'getConceptByKeyword2' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchMode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'outlang', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getConceptByKeyword2
'getTermsByCodesAndLanguage' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'termcode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'codeName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermsByCodesAndLanguage
'getAgrovocCSModules' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
    ], # end parameters
  }, # end getAgrovocCSModules
'getObjectPropertyRelationship' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getObjectPropertyRelationship
'simpleSearchByModeLangXML' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchMode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'outlang', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end simpleSearchByModeLangXML
'getTermCodeByTermAndLangXML' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'term', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'codeName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermCodeByTermAndLangXML
'getCodesByURI' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'Ontology', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'ConceptURI', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'CodeName', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getCodesByURI
'simpleSearchByMode2' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchmode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'separator', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end simpleSearchByMode2
'getAllTermInSubClass' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'clsName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'OntolgoyDatabase', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getAllTermInSubClass
'getLanguageCode' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'localLang', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getLanguageCode
'getDefinitionsByClassName' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'className', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'outputlang', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getDefinitionsByClassName
'getStatusConcept' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'conceptURI', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getStatusConcept
'close' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
    ], # end parameters
  }, # end close
'getAuthoritySegment' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'integerFrom', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'integerTo', type => 'xsd:int', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getAuthoritySegment
'getWebServicesVersion' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
    ], # end parameters
  }, # end getWebServicesVersion
'getReleaseDate' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
    ], # end parameters
  }, # end getReleaseDate
'getStatusTerm' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'termCode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'codeName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getStatusTerm
'getConceptInfoByTermcodeXML' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'searchTerm', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getConceptInfoByTermcodeXML
'getTermCodeByTermXML' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'term', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermCodeByTermXML
'getTermsByClassName' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'className', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'descriptor', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'status', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermsByClassName
'getAvailableCode' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getAvailableCode
'getConceptByKeyword' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchMode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getConceptByKeyword
'reloadOWLModel' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end reloadOWLModel
'suggestTerm' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'label', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'namespace', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'parentURI', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end suggestTerm
'getFullAuthority' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchMode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getFullAuthority
'getDataTypeRelationship' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getDataTypeRelationship
'getTermExpansion' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchMode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermExpansion
'getConceptInfoByTermcode' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'termCode', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getConceptInfoByTermcode
'getTermCodeByTerm' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'term', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermCodeByTerm
'getAgrovocCSLanguagesExpand' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
    ], # end parameters
  }, # end getAgrovocCSLanguagesExpand
'getListofURI' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'uriStart', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'numResult', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getListofURI
'getLatestUpdates' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'dateFrom', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'dateTo', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getLatestUpdates
'getRelatedValuesFromConceptURIRelationURI' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'conceptURI', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'relationURI', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getRelatedValuesFromConceptURIRelationURI
'getConceptInfoByURI' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'conceptURI', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getConceptInfoByURI
'getAllLabelsByTermcode2' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'termcode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'separator', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getAllLabelsByTermcode2
'getTermsByURI' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'conceptURI', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'descriptor', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'status', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getTermsByURI
'getURIByTermAndLangXML' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'term', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchMode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getURIByTermAndLangXML
'getStatusList' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getStatusList
'getConceptByRelationshipValue' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'relationURI', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'value', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchMode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getConceptByRelationshipValue
'getConceptRelationshipList' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'clsName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'OntolgoyDatabase', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getConceptRelationshipList
'searchByModeLangScopeXML' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'searchMode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'lang', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'outlang', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'scopeid', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end searchByModeLangScopeXML
'complexSearchByTermXML' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'searchString', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'separator', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end complexSearchByTermXML
'getDefinitions' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'termcode', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'languagecode', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getDefinitions
'getConceptObject' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'clsName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'OntolgoyDatabase', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getConceptObject
'getDefinitionsByURI' => {
    endpoint => 'http://agrovoc.uniroma2.it:8080/SKOSWS/services/SKOSWS',
    soapaction => '',
    namespace => 'http://aos.aims.fao.org',
    parameters => [
      SOAP::Data->new(name => 'ontologyName', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'conceptURI', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'format', type => 'xsd:string', attr => {}),
      SOAP::Data->new(name => 'outputlang', type => 'xsd:string', attr => {}),
    ], # end parameters
  }, # end getDefinitionsByURI
); # end my %methods

use SOAP::Lite;
use Exporter;
use Carp ();

use vars qw(@ISA $AUTOLOAD @EXPORT_OK %EXPORT_TAGS);
@ISA = qw(Exporter SOAP::Lite);
@EXPORT_OK = (keys %methods);
%EXPORT_TAGS = ('all' => [@EXPORT_OK]);

sub _call {
    my ($self, $method) = (shift, shift);
    my $name = UNIVERSAL::isa($method => 'SOAP::Data') ? $method->name : $method;
    my %method = %{$methods{$name}};
    $self->proxy($method{endpoint} || Carp::croak "No server address (proxy) specified")
        unless $self->proxy;
    my @templates = @{$method{parameters}};
    my @parameters = ();
    foreach my $param (@_) {
        if (@templates) {
            my $template = shift @templates;
            my ($prefix,$typename) = SOAP::Utils::splitqname($template->type);
            my $method = 'as_'.$typename;
            # TODO - if can('as_'.$typename) {...}
            my $result = $self->serializer->$method($param, $template->name, $template->type, $template->attr);
            push(@parameters, $template->value($result->[2]));
        }
        else {
            push(@parameters, $param);
        }
    }
    $self->endpoint($method{endpoint})
       ->ns($method{namespace})
       ->on_action(sub{qq!"$method{soapaction}"!});
  $self->serializer->register_ns("http://xml.apache.org/xml-soap","apachesoap");
  $self->serializer->register_ns("http://aos.aims.fao.org","intf");
  $self->serializer->register_ns("http://aos.aims.fao.org","impl");
  $self->serializer->register_ns("http://schemas.xmlsoap.org/wsdl/","wsdl");
  $self->serializer->register_ns("http://www.w3.org/2001/XMLSchema","xsd");
    my $som = $self->SUPER::call($method => @parameters);
    if ($self->want_som) {
        return $som;
    }
    UNIVERSAL::isa($som => 'SOAP::SOM') ? wantarray ? $som->paramsall : $som->result : $som;
}

sub BEGIN {
    no strict 'refs';
    for my $method (qw(want_som)) {
        my $field = '_' . $method;
        *$method = sub {
            my $self = shift->new;
            @_ ? ($self->{$field} = shift, return $self) : return $self->{$field};
        }
    }
}
no strict 'refs';
for my $method (@EXPORT_OK) {
    my %method = %{$methods{$method}};
    *$method = sub {
        my $self = UNIVERSAL::isa($_[0] => __PACKAGE__)
            ? ref $_[0]
                ? shift # OBJECT
                # CLASS, either get self or create new and assign to self
                : (shift->self || __PACKAGE__->self(__PACKAGE__->new))
            # function call, either get self or create new and assign to self
            : (__PACKAGE__->self || __PACKAGE__->self(__PACKAGE__->new));
        $self->_call($method, @_);
    }
}

sub AUTOLOAD {
    my $method = substr($AUTOLOAD, rindex($AUTOLOAD, '::') + 2);
    return if $method eq 'DESTROY' || $method eq 'want_som';
    die "Unrecognized method '$method'. List of available method(s): @EXPORT_OK\n";
}

1;
