<div id="recordedbooks-checkout" class="modal" tabindex="-1" role="dialog" aria-labelledby="recordedbooks-checkout-label" aria-hidden="true">
 <div class="modal-header">
 <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
 <h3 id="recordedbooks-checkout-label">Issue</h3>
 </div>
 <form action="#" method="post" id="recordedbooks-checkout-form">
 <div class="modal-body">
 <input type="hidden" name="id" value="" />
 </div>
 <div class="modal-footer">
 <input class="btn btn-default recordedbooks-checkout-submit" type="submit" value="Issue" />
 <a href="#" data-dismiss="modal" aria-hidden="true" class="cancel">Cancel</a>
 </div>
 </form> <!-- /#recordedbooks-checkout-form -->
</div> <!-- /#recordedbooks-checkout -->
