---
advancededitormacro_id_pp:
  $ref: parameters/advancededitormacro.yaml#/advancededitormacro_id_pp
biblio_id_pp:
  $ref: parameters/biblio.yaml#/biblio_id_pp
booking_id_pp:
  $ref: parameters/booking.yaml#/booking_id_pp
cash_register_id_pp:
  $ref: parameters/cash_register.yaml#/cash_register_id_pp
cashup_id_pp:
  $ref: parameters/cashup.yaml#/cashup_id_pp
checkout_id_pp:
  $ref: parameters/checkout.yaml#/checkout_id_pp
city_id_pp:
  $ref: parameters/city.yaml#/city_id_pp
club_id_pp:
  $ref: parameters/club.yaml#/club_id_pp
fund_id_pp:
  $ref: parameters/fund.yaml#/fund_id_pp
hold_id_pp:
  $ref: parameters/hold.yaml#/hold_id_pp
import_batch_profile_id_pp:
  $ref: parameters/import_batch_profile.yaml#/import_batch_profile_id_pp
item_id_pp:
  $ref: parameters/item.yaml#/item_id_pp
library_id_pp:
  $ref: parameters/library.yaml#/library_id_pp
match:
  name: _match
  in: query
  required: false
  description: Matching criteria
  type: string
  enum:
    - contains
    - exact
    - starts_with
    - ends_with
order_by:
  name: _order_by
  in: query
  required: false
  description: Sorting criteria
  type: array
  collectionFormat: csv
  items:
    type: string
order_id_pp:
  $ref: parameters/order.yaml#/order_id_pp
page:
  name: _page
  in: query
  required: false
  description: Page number, for paginated object listing
  type: integer
patron_id_pp:
  $ref: parameters/patron.yaml#/patron_id_pp
patron_id_qp:
  $ref: parameters/patron.yaml#/patron_id_qp
per_page:
  name: _per_page
  in: query
  required: false
  description: Page size, for paginated object listing
  type: integer
q_body:
  name: query
  in: body
  required: false
  description: Query filter sent through request's body
  schema:
    type:
      - object
      - array
q_param:
  name: q
  in: query
  required: false
  description: Query filter sent as a request parameter
  type: string
q_header:
  name: x-koha-query
  in: header
  required: false
  description: Query filter sent as a request header
  type: string
quote_id_pp:
  $ref: parameters/quote.yaml#/quote_id_pp
seen_pp:
  $ref: parameters/checkout.yaml#/seen_pp
smtp_server_id_pp:
  $ref: parameters/smtp_server.yaml#/smtp_server_id_pp
suggestion_id_pp:
  $ref: parameters/suggestion.yaml#/suggestion_id_pp
transfer_limit_id_pp:
  $ref: parameters/transfer_limit.yaml#/transfer_limit_id_pp
vendor_id_pp:
  $ref: parameters/vendor.yaml#/vendor_id_pp
