modules:
  acqui:
    histsearch:
      histsearcht:
        -
          columnname: order_line
        -
          columnname: status
        -
          columnname: basket
        -
          columnname: basket_creator
        -
          columnname: basket_group
        -
          columnname: invoice_number
        -
          columnname: summary
        -
          columnname: vendor
        -
          columnname: placed_on
        -
          columnname: received_on
        -
          columnname: quantity_received
        -
          columnname: pending_order
        -
          columnname: unit_cost
        -
          columnname: fund

    lateorders:
      late_orders:
        -
          columnname: checkbox
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: order_date
        -
          columnname: estimated_delivery_date
        -
          columnname: vendor
        -
          columnname: information
        -
          columnname: total_cost
        -
          columnname: basket
        -
          columnname: basket_group
        -
          columnname: library
        -
          columnname: fund
        -
          columnname: claims_count
        -
          columnname: claimed_date
    basket:
      orders:
        -
          columnname: basket_number
        -
          columnname: order_information
        -
          columnname: recommended_retail_price_tax_excluded
        -
          columnname: ecost_tax_excluded
        -
          columnname: recommended_retail_price_tax_included
          is_hidden: 1
        -
          columnname: ecost_tax_included
          is_hidden: 1
        -
          columnname: replacement_price
        -
          columnname: quantity
        -
          columnname: total_tax_excluded
        -
          columnname: total_tax_included
          is_hidden: 1
        -
          columnname: goods_and_services_tax_percentage
        -
          columnname: goods_and_services_tax
        -
          columnname: fund
        -
          columnname: supplier_report
        -
          columnname: modify
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: cancel
          cannot_be_toggled: 1
          cannot_be_modified: 1

  admin:
    currency:
      currencies-table:
        -
          columnname: currency
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: rate
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: symbol
        -
          columnname: iso_code
          is_hidden: 1
        -
          columnname: last_updated
        -
          columnname: active
        -
          columnname: actions

  catalogue:
    detail:
      acquisitiondetails-table:
        -
          columnname: vendor
        -
          columnname: invoice
        -
          columnname: basketgroup
        -
          columnname: basket
        -
          columnname: ordernumber
        -
          columnname: creation_date
        -
          columnname: received_data
        -
          columnname: status
        -
          columnname: quantity
        -
          columnname: subscription
        -
          columnname: subscription_callnumber

      checkoutshistory-table:
        -
          columnname: patron
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: barcode
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: checked_out_from
        -
          columnname: renewed
        -
          columnname: checkout_on
        -
          columnname: due_date
        -
          columnname: checkin_on

  cataloguing:
    additem:
      itemst:
        # NOTE: These columns are in the same order as kohastructure.sql, and contain all items
        # columns except for the following internal/obsolete fields: stack, more_subfields_xml,
        # cn_sort, permanent_location, damaged_on itemlost_on, withdrawn_on, issues, renewals and
        # reserves.
        -
          columnname: barcode
        -
          columnname: dateaccessioned
        -
          columnname: booksellerid
        -
          columnname: homebranch
        -
          columnname: price
        -
          columnname: replacementprice
        -
          columnname: replacementpricedate
        -
          columnname: datelastborrowed
        -
          columnname: datelastseen
        -
          columnname: stack
        -
          columnname: notforloan
        -
          columnname: damaged
        -
          columnname: itemlost
        -
          columnname: withdrawn
        -
          columnname: itemcallnumber
        -
          columnname: coded_location_qualifier
        -
          columnname: restricted
        -
          columnname: itemnotes
        -
          columnname: itemnotes_nonpublic
        -
          columnname: holdingbranch
        -
          columnname: paidfor
        -
          columnname: timestamp
        -
          columnname: location
        -
          columnname: onloan
        -
          columnname: cn_source
        -
          columnname: ccode
        -
          columnname: materials
        -
          columnname: uri
        -
          columnname: itype
        -
          columnname: enumchron
        -
          columnname: copynumber
        -
          columnname: stocknumber

  coursereserves:
    courses:
      course_reserves_table:
        -
          columnname: name
        -
          columnname: department
        -
          columnname: course_no
        -
          columnname: section
        -
          columnname: term
        -
          columnname: instructors
        -
          columnname: staff_note
        -
          columnname: public_note
        -
          columnname: no_of_students
        -
          columnname: enabled

    reserves:
      course_reserves_table:
        -
          columnname: title
        -
         columnname: author
        -
          columnname: barcode
        -
          columnname: call_number
        -
          columnname: item_type
        -
          columnname: collection
        -
          columnname: location
        -
          columnname: library
        -
          columnname: staff_note
        -
          columnname: public_note
        -
          columnname: link
        -
          columnname: other_course_reserves
        -
          columnname: actions
          cannot_be_toggled: 1
          cannot_be_modified: 1

  illrequests:
    ill-requests:
      ill-requests:
        -
          columnname: illrequest_id
        -
          columnname: metadata_Author
        -
          columnname: metadata_Title
        -
          columnname: metadata_Item_part_title
        -
          columnname: metadata_Issue
        -
          columnname: metadata_Volume
        -
          columnname: metadata_Year
        -
          columnname: metadata_Item_part_pages
        -
          columnname: metadata_Type
        -
          columnname: orderid
        -
          columnname: patron_borrowernumber
        -
          columnname: patron_cardnumber
        -
          columnname: biblio_id
        -
          columnname: borrowernumber
        -
          columnname: library_branchname
        -
          columnname: status
        -
          columnname: placed
        -
          columnname: replied
        -
          columnname: updated
        -
          columnname: completed
        -
          columnname: accessurl
        -
          columnname: cost
        -
          columnname: notesopac
        -
          columnname: notesstaff
        -
          columnname: backend
        -
          columnname: action
          cannot_be_toggled: 1
          cannot_be_modified: 1

  members:
    fines:
      account-fines:
        -
          columnname: date
        -
          columnname: description
        -
          columnname: note
        -
          columnname: amount
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: amountoutstanding
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: actions
          cannot_be_toggled: 1
          cannot_be_modified: 1

    member:
      memberresultst:
        -
          columnname: checkbox
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: cardnumber
        -
          columnname: name
        -
          columnname: dateofbirth
        -
          columnname: category
        -
          columnname: library
        -
          columnname: expires_on
        -
          columnname: od_checkouts
        -
          columnname: fines
        -
          columnname: circ_notes
        -
          columnname: actions
          cannot_be_toggled: 1
          cannot_be_modified: 1

    moremember:
      issues-table:
        -
          columnname: sort_order
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: todays_or_previous_checkouts
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: due_date_unformatted
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: due_date
        -
          columnname: title
        -
          columnname: item_type
        -
          columnname: collection
        -
          columnname: location
        -
          columnname: homebranch
        -
          columnname: checkout_on_unformatted
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: checkout_on
        -
          columnname: checkout_from
        -
          columnname: callno
        -
          columnname: charge
        -
          columnname: fine
        -
          columnname: price
        -
          columnname: renew
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: checkin
        -
          columnname: export
          cannot_be_toggled: 1
          cannot_be_modified: 1

    holdshistory:
      holdshistory-table:
        -
          columnname: title
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: author
        -
          columnname: barcode
        -
          columnname: branch
        -
          columnname: reservedate
        -
          columnname: expirationdate
        -
          columnname: waitingdate
        -
          columnname: cancellationdate
        -
          columnname: itemtype
        -
          columnname: status

  reports:
    lostitems:
      lostitems-table:
        -
          columnname: title
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: author
        -
          columnname: lostcode
        -
          columnname: itemlost_on
        -
          columnname: barcode
        -
          columnname: callnumber
        -
          columnname: datelastseen
        -
          columnname: price
        -
          columnname: replacementprice
        -
          columnname: library
        -
          columnname: itemtype
        -
          columnname: current_location
        -
          columnname: location
        -
          columnname: notforloan
        -
          columnname: notes

    saved-sql:
      table_reports:
        -
          columnname: selection
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: report_id
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: report_name
        -
          columnname: type
        -
          columnname: group
        -
          columnname: subgroup
        -
          columnname: notes
        -
          columnname: author
        -
          columnname: creation_date
        -
          columnname: last_edit
        -
          columnname: last_run
        -
          columnname: public
        -
          columnname: json_url
        -
          columnname: cache_expiry
        -
          columnname: saved_results
        -
          columnname: update
        -
          columnname: actions
          cannot_be_toggled: 1
          cannot_be_modified: 1

  circ:
    circulation:
      issues-table:
        -
          columnname: sort_order
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: todays_or_previous_checkouts
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: due_date_unformatted
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: due_date
        -
          columnname: title
        -
          columnname: item_type
        -
          columnname: collection
        -
          columnname: location
        -
          columnname: homebranch
        -
          columnname: checkout_on_unformatted
          cannot_be_toggled: 1
          cannot_be_modified: 1
          is_hidden: 1
        -
          columnname: checkout_on
        -
          columnname: checkout_from
        -
          columnname: callno
        -
          columnname: charge
        -
          columnname: fine
        -
          columnname: price
        -
          columnname: renew
          cannot_be_toggled: 1
          cannot_be_modified: 1
        -
          columnname: checkin
        -
          columnname: export
          cannot_be_toggled: 1
          cannot_be_modified: 1

    returns:
      checkedintable:
        -
          columnname: due_date
        -
          columnname: title
        -
          columnname: author
        -
          columnname: barcode
        -
          columnname: homelibrary
        -
          columnname: holdinglibrary
        -
          columnname: location
        -
          columnname: itemcallnumber
        -
          columnname: dateaccessioned
          is_hidden: 1
        -
          columnname: itype
        -
          columnname: borrower
        -
          columnname: itemnote

    view_holdsqueue:
      holds-table:
        -
          columnname: title
        -
          columnname: collection
        -
          columnname: document_type
        -
          columnname: callnumber
        -
          columnname: copynumber
        -
          columnname: enumeration
        -
          columnname: barcode
        -
          columnname: patron
        -
          columnname: send_to
        -
          columnname: date
        -
          columnname: notes

    holds:
      holds-to-pull:
        -
          columnname: pull_items
        -
          columnname: avalaible_items
        -
          columnname: patrons
        -
          columnname: patron
        -
          columnname: title
        -
          columnname: libraries
        -
          columnname: call_numbers
        -
          columnname: copy_numbers
        -
          columnname: enumeration
        -
          columnname: itemtypes
        -
          columnname: locations
        -
          columnname: hold_date
        -
          columnname: action

  opac:
    biblio-detail:
      holdingst:
        -
          columnname: item_itemtype
        -
          columnname: item_current_location
        -
          columnname: item_home_location
        -
          columnname: item_shelving_location
          is_hidden: 1
        -
          columnname: item_ccode
        -
          columnname: item_callnumber
        -
          columnname: item_enumchron
        -
          columnname: item_url
        -
          columnname: item_copy
        -
          columnname: item_status
        -
          columnname: item_notes
        -
          columnname: item_datedue
        -
          columnname: item_barcode
          is_hidden: 1
        -
          columnname: item_holds
        -
          columnname: item_priority
        -
          columnname: item_coursereserves

      subscriptionst:
        -
          columnname: serial_serialseq
        -
          columnname: serial_publisheddate
        -
          columnname: serial_planneddate
        -
          columnname: serial_status
        -
          columnname: serial_notes

  serials:
    subscription-detail:
      orders:
        -
          columnname: invoice
        -
          columnname: basket
        -
          columnname: ordernumber
        -
          columnname: creation_date
        -
          columnname: receive_date
        -
          columnname: status
        -
          columnname: order_internalnote
        -
          columnname: order_vendornote
        -
          columnname: fund
        -
          columnname: ordered
        -
          columnname: spent

  tools:
    notices:
      lettert:
        -
          columnname: library
        -
          columnname: module
        -
          columnname: code
        -
          columnname: name
        -
          columnname: copy_notice
        -
          columnname: actions
          cannot_be_toggled: 1
          cannot_be_modified: 1
